apiVersion: v1
kind: Service
metadata:
   name: my-lb1
   labels:
    app:  devblogweb
spec:
  type: NodePort
  selector:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort:  30000